#!/bin/bash
# Script: Analyze Homepage Configuration
# Purpose: Comprehensive analysis of Drupal homepage configuration
# Returns: JSON object with homepage path, type, blocks, views, Layout Builder info

# Verify DOCROOT is set
if [ -z "$DOCROOT" ]; then
    echo "{}"
    exit 0
fi

# ============================================
# Function: Get homepage configuration
# ============================================
get_homepage_config() {
    ddev drush config:get system.site page.front --format=json 2>/dev/null || echo "{}"
}

# ============================================
# Function: Detect homepage type and details
# ============================================
get_homepage_type() {
    ddev drush eval "
        \$config = \\Drupal::config('system.site');
        \$front_page = \$config->get('page.front');

        \$result = [
            'configured_path' => \$front_page ?: '/node',
            'type' => 'unknown',
            'description' => '',
            'details' => []
        ];

        // Determine homepage type
        if (empty(\$front_page) || \$front_page === '/node') {
            \$result['type'] = 'default_promoted';
            \$result['description'] = 'Default Drupal homepage showing promoted nodes';

            // Count promoted nodes
            \$query = \\Drupal::entityQuery('node')
                ->condition('promote', 1)
                ->condition('status', 1)
                ->accessCheck(FALSE);
            \$count = \$query->count()->execute();
            \$result['details']['promoted_nodes_count'] = (int)\$count;

        } elseif (preg_match('/^\\/?node\\/(\\d+)$/', \$front_page, \$matches)) {
            \$nid = \$matches[1];
            \$node = \\Drupal::entityTypeManager()->getStorage('node')->load(\$nid);

            if (\$node) {
                \$result['type'] = 'static_node';
                \$result['description'] = 'Homepage is a specific node/page';
                \$result['details'] = [
                    'node_id' => (int)\$nid,
                    'title' => \$node->getTitle(),
                    'content_type' => \$node->bundle(),
                    'status' => \$node->isPublished() ? 'published' : 'unpublished',
                    'created' => date('Y-m-d H:i:s', \$node->getCreatedTime()),
                    'updated' => date('Y-m-d H:i:s', \$node->getChangedTime())
                ];

                // Check if Layout Builder is enabled
                if (\$node->hasField('layout_builder__layout')) {
                    \$layout_enabled = !\$node->get('layout_builder__layout')->isEmpty();
                    \$result['details']['layout_builder_enabled'] = \$layout_enabled;

                    if (\$layout_enabled) {
                        \$sections = \$node->get('layout_builder__layout')->getValue();
                        \$result['details']['layout_sections_count'] = count(\$sections);
                    }
                }
            } else {
                \$result['type'] = 'static_node_missing';
                \$result['description'] = 'Homepage points to non-existent node';
                \$result['details']['node_id'] = (int)\$nid;
                \$result['details']['error'] = 'Node does not exist';
            }

        } else {
            // Check if it's a view
            \$is_view = false;
            \$views = \\Drupal\\views\\Views::getAllViews();
            foreach (\$views as \$view) {
                if (\$view->status()) {
                    foreach (\$view->get('display') as \$display_id => \$display) {
                        \$path = \$display['display_options']['path'] ?? null;
                        \$normalized_path = '/' . ltrim(\$path, '/');
                        \$normalized_front = '/' . ltrim(\$front_page, '/');

                        if (\$path && (\$normalized_path === \$normalized_front || \$path === '<front>' || \$path === 'home')) {
                            \$is_view = true;
                            \$result['type'] = 'view_based';
                            \$result['description'] = 'Homepage is generated by a View';
                            \$result['details'] = [
                                'view_id' => \$view->id(),
                                'view_label' => \$view->label(),
                                'display_id' => \$display_id,
                                'display_title' => \$display['display_title'] ?? 'Unknown',
                                'display_plugin' => \$display['display_plugin'] ?? 'unknown',
                                'path' => \$path
                            ];

                            // Get items per page
                            if (isset(\$display['display_options']['pager']['options']['items_per_page'])) {
                                \$result['details']['items_per_page'] = (int)\$display['display_options']['pager']['options']['items_per_page'];
                            }

                            // Count exposed filters
                            if (isset(\$display['display_options']['filters'])) {
                                \$exposed_count = 0;
                                foreach (\$display['display_options']['filters'] as \$filter) {
                                    if (isset(\$filter['exposed']) && \$filter['exposed']) {
                                        \$exposed_count++;
                                    }
                                }
                                \$result['details']['exposed_filters_count'] = \$exposed_count;
                            }
                            break 2;
                        }
                    }
                }
            }

            if (!\$is_view) {
                // Try to resolve the route
                try {
                    \$path_to_check = \$front_page;
                    if (strpos(\$path_to_check, '/') !== 0) {
                        \$path_to_check = '/' . \$path_to_check;
                    }

                    \$route_provider = \\Drupal::service('router.route_provider');
                    \$routes = \$route_provider->getRoutesByPattern(\$path_to_check);

                    if (\$routes->count() > 0) {
                        foreach (\$routes as \$route_name => \$route) {
                            \$result['type'] = 'custom_route';
                            \$result['description'] = 'Homepage uses custom route or controller';
                            \$result['details']['route_name'] = \$route_name;
                            \$result['details']['path'] = \$path_to_check;

                            // Detect delivery mechanism
                            if (strpos(\$route_name, 'page_manager.') === 0) {
                                \$result['details']['delivery'] = 'page_manager';
                            } elseif (strpos(\$route_name, 'panels.') === 0 || strpos(\$route_name, 'panel.') === 0) {
                                \$result['details']['delivery'] = 'panels';
                            } elseif (strpos(\$route_name, 'entity.config_pages.') === 0) {
                                \$result['details']['delivery'] = 'config_pages';
                            } else {
                                \$result['details']['delivery'] = 'custom_controller';
                            }

                            \$controller = \$route->getDefault('_controller');
                            \$form = \$route->getDefault('_form');
                            \$entity_view = \$route->getDefault('_entity_view');

                            if (\$controller) {
                                \$result['details']['controller'] = \$controller;
                            }
                            if (\$form) {
                                \$result['details']['form'] = \$form;
                            }
                            if (\$entity_view) {
                                \$result['details']['entity_view'] = \$entity_view;
                            }

                            break;
                        }
                    } else {
                        \$result['type'] = 'unknown';
                        \$result['description'] = 'Could not resolve route';
                        \$result['details']['error'] = 'Route not found for path: ' . \$front_page;
                    }
                } catch (Exception \$e) {
                    \$result['type'] = 'error';
                    \$result['description'] = 'Error resolving route';
                    \$result['details']['error'] = \$e->getMessage();
                }
            }
        }

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Function: Get blocks placed on homepage
# ============================================
get_homepage_blocks() {
    ddev drush eval "
        \$theme = \\Drupal::config('system.theme')->get('default');
        \$blocks = \\Drupal::entityTypeManager()->getStorage('block')->loadByProperties(['theme' => \$theme]);

        \$result = [
            'theme' => \$theme,
            'total_active_blocks' => 0,
            'regions' => []
        ];

        foreach (\$blocks as \$block) {
            if (\$block->status()) {
                \$result['total_active_blocks']++;
                \$region = \$block->getRegion();

                if (!isset(\$result['regions'][\$region])) {
                    \$result['regions'][\$region] = [];
                }

                \$plugin_id = \$block->getPluginId();
                \$plugin_type = 'other';

                if (strpos(\$plugin_id, 'block_content:') === 0) {
                    \$plugin_type = 'custom_block';
                } elseif (strpos(\$plugin_id, 'system_') === 0) {
                    \$plugin_type = 'system';
                } elseif (strpos(\$plugin_id, 'views_block:') === 0) {
                    \$plugin_type = 'views';
                } elseif (strpos(\$plugin_id, 'menu_block:') === 0) {
                    \$plugin_type = 'menu';
                }

                \$result['regions'][\$region][] = [
                    'id' => \$block->id(),
                    'label' => \$block->label(),
                    'plugin_id' => \$plugin_id,
                    'plugin_type' => \$plugin_type,
                    'weight' => \$block->getWeight()
                ];
            }
        }

        // Sort blocks by weight within each region
        foreach (\$result['regions'] as \$region => \$blocks_list) {
            usort(\$blocks_list, function(\$a, \$b) {
                return \$a['weight'] <=> \$b['weight'];
            });
            \$result['regions'][\$region] = \$blocks_list;
        }

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Function: Get Page Manager status
# ============================================
get_page_manager_status() {
    ddev drush eval "
        \$result = [
            'module_enabled' => false,
            'pages' => [],
            'homepage_override' => false
        ];

        if (\\Drupal::moduleHandler()->moduleExists('page_manager')) {
            \$result['module_enabled'] = true;

            \$page_storage = \\Drupal::entityTypeManager()->getStorage('page');
            \$pages = \$page_storage->loadMultiple();

            foreach (\$pages as \$page) {
                \$path = \$page->getPath();
                \$page_info = [
                    'id' => \$page->id(),
                    'label' => \$page->label(),
                    'path' => \$path,
                    'is_homepage' => in_array(\$path, ['/', '<front>', '/node'])
                ];

                if (\$page_info['is_homepage']) {
                    \$result['homepage_override'] = true;
                }

                \$result['pages'][] = \$page_info;
            }
        }

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Function: Get Layout Builder info
# ============================================
get_layout_builder_info() {
    ddev drush eval "
        \$result = [
            'module_enabled' => false,
            'homepage_uses_layout_builder' => false,
            'details' => []
        ];

        \$layout_builder_enabled = \\Drupal::moduleHandler()->moduleExists('layout_builder');
        \$result['module_enabled'] = \$layout_builder_enabled;

        if (\$layout_builder_enabled) {
            \$front_page = \\Drupal::config('system.site')->get('page.front');

            if (preg_match('/^\\/?node\\/(\\d+)$/', \$front_page, \$matches)) {
                \$nid = \$matches[1];
                \$node = \\Drupal::entityTypeManager()->getStorage('node')->load(\$nid);

                if (\$node && \$node->hasField('layout_builder__layout')) {
                    \$layout_enabled = !\$node->get('layout_builder__layout')->isEmpty();

                    if (\$layout_enabled) {
                        \$result['homepage_uses_layout_builder'] = true;
                        \$sections = \$node->get('layout_builder__layout')->getValue();
                        \$result['details'] = [
                            'layout_type' => 'custom_per_node',
                            'sections_count' => count(\$sections)
                        ];
                    }
                }
            }
        }

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Function: Get homepage metadata
# ============================================
get_homepage_metadata() {
    ddev drush eval "
        \$config = \\Drupal::config('system.site');

        \$result = [
            'site_name' => \$config->get('name'),
            'site_slogan' => \$config->get('slogan') ?: '',
            'site_email' => \$config->get('mail'),
            'page_403' => \$config->get('page.403') ?: '/user/login',
            'page_404' => \$config->get('page.404') ?: ''
        ];

        // Get path alias for homepage
        \$front_page = \$config->get('page.front') ?: '/node';
        \$path_alias_manager = \\Drupal::service('path_alias.manager');
        \$alias = \$path_alias_manager->getAliasByPath(\$front_page);

        \$result['homepage_system_path'] = \$front_page;
        \$result['homepage_alias'] = \$alias !== \$front_page ? \$alias : '';

        // Get full URL
        try {
            \$base_url = \\Drupal::request()->getSchemeAndHttpHost();
            \$result['homepage_full_url'] = \$base_url . \$alias;
        } catch (Exception \$e) {
            \$result['homepage_full_url'] = '';
        }

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Function: Check installed page builder modules
# ============================================
get_page_builder_modules() {
    ddev drush eval "
        \$modules_to_check = [
            'layout_builder' => 'Layout Builder',
            'page_manager' => 'Page Manager',
            'panels' => 'Panels',
            'panelizer' => 'Panelizer',
            'paragraphs' => 'Paragraphs',
            'block_content' => 'Custom Block Library'
        ];

        \$result = [];
        foreach (\$modules_to_check as \$module_name => \$module_label) {
            \$result[\$module_name] = [
                'label' => \$module_label,
                'installed' => \\Drupal::moduleHandler()->moduleExists(\$module_name)
            ];
        }

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Function: Get statistics
# ============================================
get_statistics() {
    ddev drush eval "
        \$front_page = \\Drupal::config('system.site')->get('page.front') ?: '/node';

        // Determine type for statistics
        \$type = 'unknown';
        if (empty(\$front_page) || \$front_page === '/node') {
            \$type = 'default_promoted';
        } elseif (preg_match('/^\\/?node\\/(\\d+)$/', \$front_page)) {
            \$type = 'static_node';
        } else {
            // Check if it's a view
            \$views = \\Drupal\\views\\Views::getAllViews();
            foreach (\$views as \$view) {
                if (\$view->status()) {
                    foreach (\$view->get('display') as \$display_id => \$display) {
                        \$path = \$display['display_options']['path'] ?? null;
                        \$normalized_path = '/' . ltrim(\$path, '/');
                        \$normalized_front = '/' . ltrim(\$front_page, '/');
                        if (\$path && (\$normalized_path === \$normalized_front || \$path === '<front>')) {
                            \$type = 'view_based';
                            break 2;
                        }
                    }
                }
            }
            if (\$type === 'unknown') {
                \$type = 'custom_route';
            }
        }

        // Count blocks
        \$theme = \\Drupal::config('system.theme')->get('default');
        \$blocks = \\Drupal::entityTypeManager()->getStorage('block')->loadByProperties(['theme' => \$theme]);
        \$active_count = 0;
        foreach (\$blocks as \$block) {
            if (\$block->status()) {
                \$active_count++;
            }
        }

        \$result = [
            'homepage_path' => \$front_page,
            'homepage_type' => \$type,
            'active_blocks_count' => \$active_count,
            'layout_builder_installed' => \\Drupal::moduleHandler()->moduleExists('layout_builder'),
            'page_manager_installed' => \\Drupal::moduleHandler()->moduleExists('page_manager'),
            'panels_installed' => \\Drupal::moduleHandler()->moduleExists('panels')
        ];

        echo json_encode(\$result, JSON_PRETTY_PRINT);
    " 2>/dev/null || echo "{}"
}

# ============================================
# Main execution
# ============================================

# Build the complete JSON structure
echo "{"

# Homepage configuration
echo '"homepage_configuration": '
get_homepage_config
echo ","

# Homepage type and detection
echo '"homepage_type_detection": '
get_homepage_type
echo ","

# Blocks on homepage
echo '"blocks": '
get_homepage_blocks
echo ","

# Page Manager status
echo '"page_manager": '
get_page_manager_status
echo ","

# Layout Builder info
echo '"layout_builder": '
get_layout_builder_info
echo ","

# Homepage metadata
echo '"metadata": '
get_homepage_metadata
echo ","

# Page builder modules
echo '"page_builder_modules": '
get_page_builder_modules
echo ","

# Statistics
echo '"statistics": '
get_statistics

echo "}"
